// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teqlossdrqptkgrohofn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlcWxvc3NkcnFwdGtncm9ob2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyOTE3NTEsImV4cCI6MjA3MTg2Nzc1MX0.EqAJjRrvNK6CALwafN6RzJRik2iYUudNP7sMT9UkBnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});